// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ICEserveurMP3.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Serveur;

public interface _mp3OperationsNC
{
    boolean supprimerMP3(String titre);

    boolean rechercherMP3(String titre);

    String jouerMP3(String titre);

    String getToken();

    String getArtiste(String titre);

    String getAlbum(String nom);

    String getCompo(String nom);

    void play();

    void stop();

    void envoyerMusique(String titre, String artiste, String album, String compo, byte[] musique);

    String[] listerMP3();
}
