// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ICEserveurMP3.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Serveur;

public interface _mp3Operations
{
    boolean supprimerMP3(String titre, Ice.Current __current);

    boolean rechercherMP3(String titre, Ice.Current __current);

    String jouerMP3(String titre, Ice.Current __current);

    String getToken(Ice.Current __current);

    String getArtiste(String titre, Ice.Current __current);

    String getAlbum(String nom, Ice.Current __current);

    String getCompo(String nom, Ice.Current __current);

    void play(Ice.Current __current);

    void stop(Ice.Current __current);

    void envoyerMusique(String titre, String artiste, String album, String compo, byte[] musique, Ice.Current __current);

    String[] listerMP3(Ice.Current __current);
}
