// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ICEserveurMP3.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Serveur;

public interface _mp3OperationsNC
{
    void ajouterMP3(String nom, String url);

    boolean supprimerMP3(String nom);

    boolean rechercherMP3(String nom);

    String jouerMP3(String nom);

    String getToken();

    void play();

    void stop();

    void envoyerMusique(String nom, byte[] musique);

    String[] listerMP3();
}
