// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ICEserveurMP3.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Serveur;

public interface MoniteurPrx extends Ice.ObjectPrx
{
    public void rapport(String action, String titre);

    public void rapport(String action, String titre, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_rapport(String action, String titre);

    public Ice.AsyncResult begin_rapport(String action, String titre, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_rapport(String action, String titre, Ice.Callback __cb);

    public Ice.AsyncResult begin_rapport(String action, String titre, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_rapport(String action, String titre, Callback_Moniteur_rapport __cb);

    public Ice.AsyncResult begin_rapport(String action, String titre, java.util.Map<String, String> __ctx, Callback_Moniteur_rapport __cb);

    public void end_rapport(Ice.AsyncResult __result);
}
