// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ICEserveurMP3.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Serveur;

public final class MoniteurPrxHelper extends Ice.ObjectPrxHelperBase implements MoniteurPrx
{
    private static final String __rapport_name = "rapport";

    public void rapport(String action, String titre)
    {
        rapport(action, titre, null, false);
    }

    public void rapport(String action, String titre, java.util.Map<String, String> __ctx)
    {
        rapport(action, titre, __ctx, true);
    }

    private void rapport(String action, String titre, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "rapport", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __delBase = __getDelegate(false);
                    _MoniteurDel __del = (_MoniteurDel)__delBase;
                    __del.rapport(action, titre, __ctx, __observer);
                    return;
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_rapport(String action, String titre)
    {
        return begin_rapport(action, titre, null, false, null);
    }

    public Ice.AsyncResult begin_rapport(String action, String titre, java.util.Map<String, String> __ctx)
    {
        return begin_rapport(action, titre, __ctx, true, null);
    }

    public Ice.AsyncResult begin_rapport(String action, String titre, Ice.Callback __cb)
    {
        return begin_rapport(action, titre, null, false, __cb);
    }

    public Ice.AsyncResult begin_rapport(String action, String titre, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_rapport(action, titre, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_rapport(String action, String titre, Callback_Moniteur_rapport __cb)
    {
        return begin_rapport(action, titre, null, false, __cb);
    }

    public Ice.AsyncResult begin_rapport(String action, String titre, java.util.Map<String, String> __ctx, Callback_Moniteur_rapport __cb)
    {
        return begin_rapport(action, titre, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_rapport(String action, String titre, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __rapport_name, __cb);
        try
        {
            __result.__prepare(__rapport_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(action);
            __os.writeString(titre);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public void end_rapport(Ice.AsyncResult __result)
    {
        __end(__result, __rapport_name);
    }

    public static MoniteurPrx checkedCast(Ice.ObjectPrx __obj)
    {
        MoniteurPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof MoniteurPrx)
            {
                __d = (MoniteurPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    MoniteurPrxHelper __h = new MoniteurPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static MoniteurPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        MoniteurPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof MoniteurPrx)
            {
                __d = (MoniteurPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    MoniteurPrxHelper __h = new MoniteurPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static MoniteurPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        MoniteurPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    MoniteurPrxHelper __h = new MoniteurPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static MoniteurPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        MoniteurPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    MoniteurPrxHelper __h = new MoniteurPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static MoniteurPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        MoniteurPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof MoniteurPrx)
            {
                __d = (MoniteurPrx)__obj;
            }
            else
            {
                MoniteurPrxHelper __h = new MoniteurPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static MoniteurPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        MoniteurPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            MoniteurPrxHelper __h = new MoniteurPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::Serveur::Moniteur"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _MoniteurDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _MoniteurDelD();
    }

    public static void __write(IceInternal.BasicStream __os, MoniteurPrx v)
    {
        __os.writeProxy(v);
    }

    public static MoniteurPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            MoniteurPrxHelper result = new MoniteurPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
