// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ICEserveurMP3.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Serveur;

public interface mp3Prx extends Ice.ObjectPrx
{
    public void ajouterMP3(String nom, String url);

    public void ajouterMP3(String nom, String url, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_ajouterMP3(String nom, String url);

    public Ice.AsyncResult begin_ajouterMP3(String nom, String url, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_ajouterMP3(String nom, String url, Ice.Callback __cb);

    public Ice.AsyncResult begin_ajouterMP3(String nom, String url, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_ajouterMP3(String nom, String url, Callback_mp3_ajouterMP3 __cb);

    public Ice.AsyncResult begin_ajouterMP3(String nom, String url, java.util.Map<String, String> __ctx, Callback_mp3_ajouterMP3 __cb);

    public void end_ajouterMP3(Ice.AsyncResult __result);

    public boolean supprimerMP3(String nom);

    public boolean supprimerMP3(String nom, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_supprimerMP3(String nom);

    public Ice.AsyncResult begin_supprimerMP3(String nom, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_supprimerMP3(String nom, Ice.Callback __cb);

    public Ice.AsyncResult begin_supprimerMP3(String nom, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_supprimerMP3(String nom, Callback_mp3_supprimerMP3 __cb);

    public Ice.AsyncResult begin_supprimerMP3(String nom, java.util.Map<String, String> __ctx, Callback_mp3_supprimerMP3 __cb);

    public boolean end_supprimerMP3(Ice.AsyncResult __result);

    public boolean rechercherMP3(String nom);

    public boolean rechercherMP3(String nom, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_rechercherMP3(String nom);

    public Ice.AsyncResult begin_rechercherMP3(String nom, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_rechercherMP3(String nom, Ice.Callback __cb);

    public Ice.AsyncResult begin_rechercherMP3(String nom, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_rechercherMP3(String nom, Callback_mp3_rechercherMP3 __cb);

    public Ice.AsyncResult begin_rechercherMP3(String nom, java.util.Map<String, String> __ctx, Callback_mp3_rechercherMP3 __cb);

    public boolean end_rechercherMP3(Ice.AsyncResult __result);

    public void jouerMP3(String nom);

    public void jouerMP3(String nom, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_jouerMP3(String nom);

    public Ice.AsyncResult begin_jouerMP3(String nom, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_jouerMP3(String nom, Ice.Callback __cb);

    public Ice.AsyncResult begin_jouerMP3(String nom, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_jouerMP3(String nom, Callback_mp3_jouerMP3 __cb);

    public Ice.AsyncResult begin_jouerMP3(String nom, java.util.Map<String, String> __ctx, Callback_mp3_jouerMP3 __cb);

    public void end_jouerMP3(Ice.AsyncResult __result);

    public String[] listerMP3();

    public String[] listerMP3(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_listerMP3();

    public Ice.AsyncResult begin_listerMP3(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_listerMP3(Ice.Callback __cb);

    public Ice.AsyncResult begin_listerMP3(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_listerMP3(Callback_mp3_listerMP3 __cb);

    public Ice.AsyncResult begin_listerMP3(java.util.Map<String, String> __ctx, Callback_mp3_listerMP3 __cb);

    public String[] end_listerMP3(Ice.AsyncResult __result);
}
