package com.SOAP;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.5
//
// Created by Quasar Development at 15-05-2015
//
//---------------------------------------------------



public interface CMIIServiceEvents
{
    public void Starting();
    public void Completed(CMIOperationResult result);
}
